### ISSUE TITLE
补充：VSCode 简单快捷键

### ISSUE THREAD

**Issue by Ding-Fan** [egoist/blog#12]
<kbd>Ctrl</kbd> + <kbd>`</kbd>（就是 <kbd>Tab</kbd> 上面那个键） 显示 / 隐藏 Terminal

<kbd>Alt</kbd> ←/→  把光标往该方向移动一个词（在选取、多光标时非常好用）

<kbd>Alt</kbd> + <kbd>Shift</kbd> + 左键拖拽  在一列显示光标

另：Egoist 有没有尝试 VSCode 的 vim 插件？

**Comment by egoist** [comment]
回复得有些晚 😄我没怎么用 Vim
