### ISSUE TITLE
大佬是94年的是怎么做到这种程度的。

### ISSUE THREAD

**Issue by bougieL** [egoist/blog#13]
94年正常大学毕业的话到现在应该是工作两年左右。
两年创建了611多个仓库（不算fork），平均每1.178天就创建一个仓库，并且其中还有几个破千star的项目。
去年提交4115次，平均每天提交11.431次。
然后还要上班、追番，想象不出大佬是怎么做到的。
希望大佬分享一下成长经历，我也爱追动漫，玩游戏，有一颗造轮子的心。
萌新的小破站：[bougieblog.cn](https://bougieblog.cn)，期待与大佬做深入交流。

**Comment by channg** [comment]
你从哪看出来94年的

**Comment by bougieL** [comment]
> 你从哪看出来94年的

之前看她一篇博文上写的

**Comment by channg** [comment]
https://egoist.moe/about

写了

**Comment by egoist** [comment]
Fixed. https://github.com/egoist/blog/commit/a0c4f72d07b5c66de2d19f55436a1dbd395ee0cb
